spring:
  datasource:
    url: jdbc:postgresql://localhost:9100/orderdb
    username: sa
    password: abc123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Jackson warning
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: order-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: 1
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    root: INFO